spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/booking?currentSchema=booking&binaryTransfer=true&rewriteBatchedInserts=true@stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      platform: postgres
      schema-locations: classpath:init-schema.sql
      mode: always

eureka:
  instance:
    preferIpAddress: true # to use the ip address instead of the hostname
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info: # will be shown in the euereka dashboard
  app:
    name: "booking"
    description: "booking service for the charge platform"
    version: "1.0.0"