spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/booking?currentSchema=booking&binaryTransfer=true&rewriteBatchedInserts=true@stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      platform: postgres
      schema-locations: classpath:init-schema.sql
      mode: always
