server:
  port: 8072

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: "http://localhost:8075/realms/myrealm/protocol/openid-connect/certs"
#          jwk-set-uri: "http://keycloak:8080/realms/myrealm/protocol/openid-connect/certs"
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 8
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 60000 # 1 minute

resilience4j.timelimiter:
  configs:
    default:
      timeoutDuration: 5s
