server:
  port: 8072

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: "http://localhost:8070/eureka/"

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 8
      permittedNumberOfCallsInHalfOpenState: 2 # 25% of 8
      failureRateThreshold: 50 # 50%
      waitDurationInOpenState: 10000 # 10 seconds