spring:
  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/booking?currentSchema=user&binaryTransfer=true&rewriteBatchedInserts=true@stringtype=unspecified
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres
      schema-locations: classpath:init-schema.sql
      mode: always
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  instance:
    preferIpAddress: true # to use the ip address instead of the hostname
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 8
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 60000 # 1 minute


keycloak:
  server-url: http://localhost:8080
  realm: platform
  client-id: realm-management
  client-secret: o8UV0ead7xjk8vvXWiAluLbi1nt0DPmo
  username: admin
  password: admin
